# Generated by Django 6.0.3 on 2026-04-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('region', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.FloatField()),
                ('progress', models.IntegerField()),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('en_cours', 'En cours'), ('termine', 'Terminé')], max_length=20)),
            ],
        ),
    ]
