# Generated by Django 6.0.3 on 2026-04-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('education', 'Éducation'), ('sante', 'Santé'), ('eau', 'Eau & Assainissement'), ('nutrition', 'Nutrition')], default='education', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default='2024-12-31'),
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(default='Lomé', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='Description du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('actif', 'Actif'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=20),
        ),
    ]
