# Generated by Django 6.0.3 on 2026-04-25 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.activity'),
        ),
    ]
